/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ariel;

import Conexion.Configuracion;
import Controller.ClienteC;
import Model.Entity.Cliente;
import com.mysql.cj.xdevapi.Statement;
import com.sun.jdi.connect.spi.Connection;
import javax.swing.table.DefaultTableModel;
import Conexion.Conexion;
import Conexion.Configuracion;
import Controller.ProductoC;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author juan
 */
public class ClienteV extends javax.swing.JFrame {
DefaultTableModel model = new DefaultTableModel();
    /**
     * Creates new form ClienteV
     */
    public ClienteV() {
        initComponents();
         String[] titulo= new  String[]{"nombre", "Correo", "Telefono", "Direccion"};
        model.setColumnIdentifiers(titulo);
        jTable1.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Crear = new javax.swing.JButton();
        Leer = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        EliminadoFisico = new javax.swing.JButton();
        EliminadoLogico = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtID = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Nombre");

        jLabel3.setText("Correo");

        jLabel4.setText("Telefono");

        jLabel5.setText("Direccion");

        Crear.setText("Crear");
        Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearActionPerformed(evt);
            }
        });

        Leer.setText("Leer");
        Leer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeerActionPerformed(evt);
            }
        });

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        EliminadoFisico.setText("EliminadoF");
        EliminadoFisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminadoFisicoActionPerformed(evt);
            }
        });

        EliminadoLogico.setText("EliminadoL");
        EliminadoLogico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminadoLogicoActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(68, 68, 68)
                                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(23, 23, 23)))))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Crear)
                        .addGap(18, 18, 18)
                        .addComponent(Leer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Modificar)
                        .addGap(36, 36, 36)
                        .addComponent(EliminadoLogico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EliminadoFisico))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Crear)
                    .addComponent(Leer)
                    .addComponent(Modificar)
                    .addComponent(EliminadoLogico)
                    .addComponent(EliminadoFisico))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(271, 271, 271))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeerActionPerformed
                
                try {

 
            Configuracion dataConfiguration = new Configuracion();
          java.sql.Connection connection = DriverManager.getConnection(dataConfiguration.getDbURL(), dataConfiguration.getUsername(), dataConfiguration.getPassword());

            // Crear una sentencia SQL
 java.sql.Statement statement = connection.createStatement();
            // Definir la consulta SQL para seleccionar datos
            String query = "SELECT nombre, correo, telefono, direccion FROM cliente ";

            // Ejecutar la consulta
            ResultSet resultSet = statement.executeQuery(query);
            
            //limpiar la tabla
            int fila= jTable1.getRowCount();
        for(int i=fila-1; i>=0;i--){
            model.removeRow(i);
        }

            // Recorrer el conjunto de resultados
            while (resultSet.next()) {
                // Leer los valores de las columnas
                String valorColumna1 = resultSet.getString("nombre");
                String valorColumna2 = resultSet.getString("correo");
                String valorColumna3 = resultSet.getString("telefono");
                String valorColumna4 = resultSet.getString("direccion");

                // Hacer algo con los datos, por ejemplo, imprimirlos


                model.addRow(new Object[]{
                valorColumna1,valorColumna2,valorColumna3,valorColumna4
                });
                System.out.println("codigo: " + valorColumna1 + ", nombre: " + valorColumna2);
                System.out.println("precio: " + valorColumna3 + ", cantidad: " + valorColumna4);
            }

            // Cerrar la conexión y recursos

            resultSet.close();
            statement.close();
            connection.close();
        } catch (SQLException ex) {
           // Logger.getLogger(ProductoV.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_LeerActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
                        //Definir datos de entrada 
         
        String nombre;
        String correo;
        String telefono;
        String direccion;
           String  id= JOptionPane.showInputDialog("Ingrese el id del producto:");
      
  
        //Capturar datos de entrada
        Long ID = Long.parseLong(id);
        nombre = txtNombre.getText();
        correo = txtCorreo.getText();
        telefono = txtTelefono.getText();
        direccion = txtDireccion.getText();
        
        ClienteC clienteC = new ClienteC();
        clienteC.ModificarRegistro(ID, nombre, correo, telefono, direccion);
    }//GEN-LAST:event_ModificarActionPerformed

    private void CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearActionPerformed
                               //Definir datos de entrada 
        String nombre;
        String correo;
        String telefono;
        String direccion;
        

        nombre = txtNombre.getText();
        correo = txtCorreo.getText();
        telefono = txtTelefono.getText();
        direccion = txtDireccion.getText();
        
        ClienteC clienteC = new ClienteC();
        clienteC.GuardarRegistro( nombre, correo, telefono, direccion);
    }//GEN-LAST:event_CrearActionPerformed

    private void EliminadoFisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminadoFisicoActionPerformed
          String  id= JOptionPane.showInputDialog("Ingrese el id del producto:");
      
  
        //Capturar datos de entrada
        Long ID = Long.parseLong(id);
        ClienteC clienteC = new ClienteC();
        clienteC.EliminarRegistroFisico(ID);
    }//GEN-LAST:event_EliminadoFisicoActionPerformed

    private void EliminadoLogicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminadoLogicoActionPerformed
           String  id= JOptionPane.showInputDialog("Ingrese el id del producto:");
        int filaSeleccionada = jTable1.getSelectedRow();

   /*
        //Capturar datos de entrada
        iminarRegistroLogico(ID);
        Long ID = Long.parseLong(id);
        ClienteC clienteC = new ClienteC();
        clienteC.EliminarRegistroLogico(ID);
        */
         
if (filaSeleccionada >= 0) {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel(); // Obtener el modelo de la tabla

    // Obtén el valor del código de la fila seleccionada
    String nombreSelecionado = (String) model.getValueAt(filaSeleccionada, 0);

    // Llamar al controlador para eliminar el registro usando el código seleccionado
    ProductoC productoController = new ProductoC();
    productoController.EliminarLogiv(nombreSelecionado);

    // Elimina la fila seleccionada del modelo de la tabla
    model.removeRow(filaSeleccionada);
}

    }//GEN-LAST:event_EliminadoLogicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Crear;
    private javax.swing.JButton EliminadoFisico;
    private javax.swing.JButton EliminadoLogico;
    private javax.swing.JButton Leer;
    private javax.swing.JButton Modificar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
